In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [2]:
data = pd.read_csv('churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
data = data.drop(['RowNumber','CustomerId','Surname'],axis=1)
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [4]:
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [5]:
data.Geography.value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [6]:
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo = OneHotEncoder(sparse_output=False)
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']])
geo_encoded

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [7]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [8]:
geo_encoded_df = pd.DataFrame(geo_encoded,columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [9]:
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [10]:
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo,file)

In [11]:
#independent and dependent feature
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [12]:
X = data.drop('Exited',axis=1)
y = data['Exited']

In [13]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state=42)

#Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [14]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [15]:
(X_train.shape[1],)

(12,)

In [16]:
with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

In [17]:
#ANN Implementation

In [18]:
%pip install tensorboard
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

Requirement already satisfied: tensorboard in .\venv\Lib\site-packages (2.15.2)
Requirement already satisfied: absl-py>=0.4 in .\venv\Lib\site-packages (from tensorboard) (2.5.1)
Requirement already satisfied: grpcio>=1.48.2 in .\venv\Lib\site-packages (from tensorboard) (1.84.0)
Requirement already satisfied: google-auth<3,>=1.6.3 in .\venv\Lib\site-packages (from tensorboard) (2.62.0)
Requirement already satisfied: google-auth-oauthlib<2,>=0.5 in .\venv\Lib\site-packages (from tensorboard) (1.5.0)
Requirement already satisfied: markdown>=2.6.8 in .\venv\Lib\site-packages (from tensorboard) (3.11)
Requirement already satisfied: numpy>=1.12.0 in .\venv\Lib\site-packages (from tensorboard) (1.26.4)
Requirement already satisfied: protobuf!=4.24.0,>=3.19.6 in .\venv\Lib\site-packages (from tensorboard) (4.25.9)
Requirement already satisfied: requests<3,>=2.21.0 in .\venv\Lib\site-packages (from tensorboard) (2.34.2)
Requirement already satisfied: setuptools>=41.0.0 in .\venv\Lib\site-packages (from tensorboard) (65.5.0)
Requirement already satisfied: six>1.9 in .\venv\Lib\site-packages (from tensorboard) (1.17.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in .\venv\Lib\site-packages (from tensorboard) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in .\venv\Lib\site-packages (from tensorboard) (3.1.9)
Requirement already satisfied: pyasn1-modules>=0.2.1 in .\venv\Lib\site-packages (from google-auth<3,>=1.6.3->tensorboard) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in .\venv\Lib\site-packages (from google-auth<3,>=1.6.3->tensorboard) (50.0.2)
Requirement already satisfied: requests-oauthlib>=0.7.0 in .\venv\Lib\site-packages (from google-auth-oauthlib<2,>=0.5->tensorboard) (2.0.0)
Requirement already satisfied: charset_normalizer<4,>=2 in .\venv\Lib\site-packages (from requests<3,>=2.21.0->tensorboard) (3.5.2)
Requirement already satisfied: idna<4,>=2.5 in .\venv\Lib\site-packages (from requests<3,>=2.21.0->tensorboard) (3.20)
Requirement already satisfied: urllib3<3,>=1.26 in .\venv\Lib\site-packages (from requests<3,>=2.21.0->tensorboard) (2.8.0)
Requirement already satisfied: certifi>=2023.5.7 in .\venv\Lib\site-packages (from requests<3,>=2.21.0->tensorboard) (2026.7.22)
Requirement already satisfied: cffi>=2.0.0 in .\venv\Lib\site-packages (from cryptography>=38.0.3->google-auth<3,>=1.6.3->tensorboard) (2.1.1)
Requirement already satisfied: pycparser in .\venv\Lib\site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth<3,>=1.6.3->tensorboard) (3.11)
Requirement already satisfied: typing-extensions~=4.12 in .\venv\Lib\site-packages (from grpcio>=1.48.2->tensorboard) (4.16.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in .\venv\Lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard) (0.6.4)
Requirement already satisfied: oauthlib>=3.0.0 in .\venv\Lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<2,>=0.5->tensorboard) (4.0.0)
Requirement already satisfied: markupsafe>=2.1.1 in .\venv\Lib\site-packages (from werkzeug>=1.0.1->tensorboard) (3.0.4)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~etuptools (e:\UdemyFinal\Udemy_NLP\churn\venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~etuptools (e:\UdemyFinal\Udemy_NLP\churn\venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~etuptools (e:\UdemyFinal\Udemy_NLP\churn\venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~etuptools (e:\UdemyFinal\Udemy_NLP\churn\venv\Lib\site-packages)

WARNING:tensorflow:From e:\UdemyFinal\Udemy_NLP\churn\venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [19]:
model = Sequential([
    Dense(64, activation = 'relu' , input_shape = (X_train.shape[1],)),   ##HL1 connected to input layer
    Dense(32, activation = 'relu'),  ##HL2
    Dense(1, activation = 'sigmoid') ##output layer 
]
)

WARNING:tensorflow:From e:\UdemyFinal\Udemy_NLP\churn\venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [21]:
import tensorflow
opt = tensorflow.keras.optimizers.Adam(learning_rate = 0.01)
loss = tensorflow.keras.losses.BinaryCrossentropy()

In [22]:
model.compile(optimizer = opt,loss = 'binary_crossentropy', metrics = ['accuracy'])

In [23]:
#Set up the tensorboard
import os
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
log_dir = os.path.join(
    "logs",
    "fit",
    datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
)
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [24]:
#Set up early stopping
early_stopping_callback = EarlyStopping(monitor = 'val_loss' , patience = 10, restore_best_weights = True)

In [25]:
#Training the model
history = model.fit(
    X_train,y_train,
    validation_data = (X_test,y_test),
    epochs = 100,
    callbacks = [tensorboard_callback,early_stopping_callback]
)

Epoch 1/100
WARNING:tensorflow:From e:\UdemyFinal\Udemy_NLP\churn\venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From e:\UdemyFinal\Udemy_NLP\churn\venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 10s 13ms/step - loss: 0.4066 - accuracy: 0.8309 - val_loss: 0.3495 - val_accuracy: 0.8530
Epoch 2/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3542 - accuracy: 0.8535 - val_loss: 0.3530 - val_accuracy: 0.8550
Epoch 3/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3479 - accuracy: 0.8558 - val_loss: 0.3436 - val_accuracy: 0.8595
Epoch 4/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3430 - accuracy: 0.8583 - val_loss: 0.3426 - val_accuracy: 0.8615
Epoch 5/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3375 - accuracy: 0.8616 - val_loss: 0.3628 - val_accuracy: 0.8595
Epoch 6/100
250/250 [==============================] - 2s 6ms/step - loss: 0.3377 - accuracy: 0.8590 - val_loss: 0.3363 - val_accuracy: 0.8620
Epoch 7/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3350 - accuracy: 0.8622 - val_loss: 0.3533 - val_accuracy: 0.8480
Epoch 8/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3341 - accuracy: 0.8622 - val_loss: 0.3459 - val_accuracy: 0.8575
Epoch 9/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3335 - accuracy: 0.8620 - val_loss: 0.3475 - val_accuracy: 0.8555
Epoch 10/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3314 - accuracy: 0.8612 - val_loss: 0.3450 - val_accuracy: 0.8585
Epoch 11/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3263 - accuracy: 0.8659 - val_loss: 0.3540 - val_accuracy: 0.8585
Epoch 12/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3321 - accuracy: 0.8641 - val_loss: 0.3506 - val_accuracy: 0.8600
Epoch 13/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3229 - accuracy: 0.8661 - val_loss: 0.3475 - val_accuracy: 0.8600
Epoch 14/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3221 - accuracy: 0.8661 - val_loss: 0.3512 - val_accuracy: 0.8545
Epoch 15/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3212 - accuracy: 0.8709 - val_loss: 0.3556 - val_accuracy: 0.8585
Epoch 16/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3191 - accuracy: 0.8673 - val_loss: 0.3478 - val_accuracy: 0.8615

In [26]:
model.save('model.h5')

e:\UdemyFinal\Udemy_NLP\churn\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [27]:
import importlib.util
import sys

print("Python:", sys.executable)
print("setuptools:", importlib.util.find_spec("setuptools"))
print("pkg_resources:", importlib.util.find_spec("pkg_resources"))

import sys
import subprocess

subprocess.check_call([
    sys.executable,
    "-m",
    "ensurepip",
    "--upgrade"
])

subprocess.check_call([
    sys.executable,
    "-m",
    "pip",
    "install",
    "--no-cache-dir",
    "--force-reinstall",
    "setuptools==80.9.0"
])

import setuptools
import pkg_resources

print("setuptools version:", setuptools.__version__)
print("pkg_resources is available!")

Python: e:\UdemyFinal\Udemy_NLP\churn\venv\python.exe
setuptools: ModuleSpec(name='setuptools', loader=<_frozen_importlib_external.SourceFileLoader object at 0x0000018A142D2710>, origin='e:\\UdemyFinal\\Udemy_NLP\\churn\\venv\\Lib\\site-packages\\setuptools\\__init__.py', submodule_search_locations=['e:\\UdemyFinal\\Udemy_NLP\\churn\\venv\\Lib\\site-packages\\setuptools'])
pkg_resources: ModuleSpec(name='pkg_resources', loader=<_frozen_importlib_external.SourceFileLoader object at 0x0000018A5F1E9D90>, origin='e:\\UdemyFinal\\Udemy_NLP\\churn\\venv\\Lib\\site-packages\\pkg_resources\\__init__.py', submodule_search_locations=['e:\\UdemyFinal\\Udemy_NLP\\churn\\venv\\Lib\\site-packages\\pkg_resources'])

C:\Users\deepika\AppData\Local\Temp\ipykernel_1308\2731321589.py:29: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

setuptools version: 65.5.0
pkg_resources is available!

In [28]:
%pip install "setuptools<81"
import pkg_resources
print("pkg_resources is available!")

Requirement already satisfied: setuptools<81 in .\venv\Lib\site-packages (80.9.0)
Note: you may need to restart the kernel to use updated packages.
pkg_resources is available!

WARNING: Ignoring invalid distribution ~etuptools (e:\UdemyFinal\Udemy_NLP\churn\venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~etuptools (e:\UdemyFinal\Udemy_NLP\churn\venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~etuptools (e:\UdemyFinal\Udemy_NLP\churn\venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~etuptools (e:\UdemyFinal\Udemy_NLP\churn\venv\Lib\site-packages)

In [29]:
%load_ext tensorboard

In [32]:
%tensorboard --logdir logs

Reusing TensorBoard on port 6006 (pid 14988), started 4:51:33 ago. (Use '!kill 14988' to kill it.)

In [31]:
!kill 14988

kill: 14988: No such process